/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package etail;

import gui.MainMenu;

public class App {

    public static void main(String[] args) {
        // create the frame instance
        MainMenu frame = new MainMenu();

        // centre the frame on the screen
        frame.setLocationRelativeTo(null);

        // show the frame
        frame.setVisible(true);
    }
}
